name: flowter_bluetooth
description: ...
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flowter_core:
    path: ../../flowter_core

  flutter_blue_plus: 1.34.4
  win_ble: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter